/* ADD NOT NULL CONSTRAINT BACK TO VIVINO LINK WHEN DONE TROUBLESHOOTING */
DROP TABLE IF EXISTS wine_table;
CREATE TABLE wine_table (
    wine_name TEXT PRIMARY KEY,
    waitrose_link VARCHAR NOT NULL,
    vivino_link VARCHAR,
    rating INTEGER DEFAULT NULL
);